name: Build and Release Spectrum Client

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag to release (e.g. v1.2.3)"
        required: true
        type: string

jobs:
  export_spectrum:
    name: Build Spectrum Client
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: true
          fetch-depth: 0

      - name: Export Spectrum
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true 
          cache: true
          presets_to_export: windows.x86_64, macOS.universal, linux.x86.64

      - name: Create git tag
        run: |
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.version }}
          name: ${{ inputs.version }}
          generateReleaseNotes: true
          artifacts: ${{ steps.export.outputs.archive_directory }}/*

